openapi: 3.0.3
info:
  title: Task Management API
  description: Backend API for task management operations with user ownership
  version: 1.0.0
paths:
  /users/{user_id}/tasks:
    get:
      summary: List all tasks for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user whose tasks to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: User not found
    post:
      summary: Create a new task for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user creating the task
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '404':
          description: User not found
  /users/{user_id}/tasks/{task_id}:
    get:
      summary: Retrieve a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task or user not found
    put:
      summary: Update a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '404':
          description: Task or user not found
    delete:
      summary: Delete a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task or user not found
  /users/{user_id}/tasks/{task_id}/toggle:
    patch:
      summary: Toggle task completion status
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: ID of the task to toggle
          schema:
            type: integer
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task or user not found
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          description: Optional task description
        completed:
          type: boolean
          description: Whether the task is completed
        user_id:
          type: integer
          description: ID of the user who owns this task
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Task last update timestamp
    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          description: Optional task description
    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: Updated task title
        description:
          type: string
          description: Updated task description
        completed:
          type: boolean
          description: Updated completion status